# Generated by Django 6.0.6 on 2026-07-05 13:47

import django.core.validators
import django.db.models.deletion
import weblog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeblogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('excerpt', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('readTime', models.PositiveIntegerField(default=5)),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to=weblog.models.upload_weblog_image)),
                ('summary', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblogs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblogs', to='weblog.weblogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WeblogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('weblog', models.ManyToManyField(related_name='tags', to='weblog.weblog')),
            ],
        ),
        migrations.CreateModel(
            name='WeblogText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('simple', 'Simple'), ('simple_ul', 'Simple Ul'), ('purple', 'Purple'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green')], default='simple', max_length=20)),
                ('header', models.TextField(blank=True, max_length=40, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('weblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='weblog.weblog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeblogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='weblog.weblog')),
            ],
            options={
                'unique_together': {('weblog', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WeblogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='weblog.weblog')),
            ],
            options={
                'unique_together': {('user', 'weblog')},
            },
        ),
    ]
