# Generated by Django 6.0.6 on 2026-07-05 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeblogRelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_weblogs', to='product.product')),
                ('weblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='weblog.weblog')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('weblog', 'product')},
            },
        ),
    ]
