# Generated by Django 6.0.6 on 2026-07-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_weblogrelatedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='excerpt',
            field=models.CharField(max_length=100),
        ),
    ]
