# Generated by Django 6.0.6 on 2026-07-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('weblog', '0003_alter_weblog_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='weblogs', through='weblog.WeblogRelatedProduct', to='product.product'),
        ),
    ]
