# Generated by Django 6.0.6 on 2026-06-13 08:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_categoryattribute_is_filter_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'variant', 'verbose_name_plural': 'variant ها'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid HEX color.')]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product'),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productattributevalue',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
