# Generated by Django 6.0.6 on 2026-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
