# Generated by Django 6.0.6 on 2026-06-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='categoryattribute',
            table='category_attribute',
        ),
    ]
