# Generated by Django 6.0.6 on 2026-06-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_table_alter_categoryattribute_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattribute',
            name='is_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
