# Generated by Django 6.0.6 on 2026-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_categoryattribute_is_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('book', 'Book'), ('shirt', 'Shirt')], max_length=50, null=True),
        ),
    ]
