# Generated by Django 6.0.6 on 2026-06-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard')], max_length=50, null=True),
        ),
    ]
