# Generated by Django 6.0.6 on 2026-07-07 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_phone_number', models.CharField(max_length=30)),
                ('number_of_products', models.IntegerField(default=500)),
                ('brand_count', models.IntegerField(default=100)),
                ('sattisfied_customer', models.IntegerField(default=4)),
                ('sattisfy_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('instagram_link', models.CharField(max_length=100)),
                ('telegram_link', models.CharField(max_length=100)),
                ('youtube_link', models.CharField(max_length=100)),
                ('twitter_link', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
