# Generated by Django 6.0.6 on 2026-07-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_sattisfy_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='support_email',
            field=models.EmailField(default='support@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram_id',
            field=models.CharField(default='sina@gmail.com', max_length=20),
            preserve_default=False,
        ),
    ]
