# Generated by Django 6.0.6 on 2026-06-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_discount_options_alter_discountusage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={},
        ),
    ]
