# Generated by Django 6.0.6 on 2026-07-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('variant_name', models.CharField(max_length=50)),
                ('variant_price', models.PositiveBigIntegerField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('failed', 'پرداخت ناموفق'), ('returned', 'مرجوع شده'), ('refunded', 'بازپرداخت شده')], default='pending', max_length=20)),
                ('total_price', models.PositiveBigIntegerField()),
                ('discount_amount', models.PositiveBigIntegerField(default=0)),
                ('final_price', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.discount')),
            ],
        ),
    ]
