# Generated by Django 6.0.6 on 2026-07-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('failed', 'پرداخت ناموفق'), ('returned', 'مرجوع شده'), ('refunded', 'بازپرداخت شده')], default='pending', max_length=20),
        ),
    ]
